### ISSUE TITLE
Fails if slo$sample_to_covariates is a data.table

### ISSUE THREAD

**Issue by alexpenson** [bartongroup/RATS#13]
Thanks for the package!

A sleuth object created with a data.table as a sample_to_covariates table leads to the following error:
```
Creating look-up structures...
Error in `[.data.table`(covariates, , varname) :
  j (the 2nd argument inside [...]) is a single symbol but column name 'varname' is not found. Perhaps you intended DT[,..varname] or DT[,varname,with=FALSE]. This difference to data.frame is deliberate and explained in FAQ 1.1.
```

This is the offending line:
`func.R#L196`

**Comment by fruce-ki** [comment]
Hello Alex!

Thank you for reporting this!
I was not aware it was possible for sleuth objects to have the covariates in data.table format.

Cheers!

Kimon

**Comment by fruce-ki** [comment]
- [ ] Update data emulator to create covariates in data.table format.
- [ ] Create unit tests to replicate issue.
- [ ] Fix offending syntax.
- [ ] Pass tests.

**Comment by fruce-ki** [comment]
@alexpenson 

Dear Alex

I just pushed a patch for the covariate parser to the current developmental version 0.3.7.
Can I ask you, please, to try it with your data and let me know if it behaves as expected?

- [ ] Patched code behaves correctly with the data the triggered the bug.

Thanks!

Kimon


PS. Instructions for obtaining the developmental version are included in the vignettes.

**Comment by alexpenson** [comment]
Yes it works 👍 
Thanks

**Comment by fruce-ki** [comment]
Awesome! I'll release the next snapshot version by the end of this month.
