### ISSUE TITLE
Directly import transcript abundances from salmon/kallisto output

### ISSUE THREAD

**Issue by jamespblloyd** [bartongroup/RATS#23]
Directly import transcript abundances (with bootstraps) from salmon output files (.sf) rather than having to import the counts into formatted datatables. This would be very useful. Especially for avoiding the very large sleuth object needed to be loaded on a machine with very limited memory. 

EDITED by developer to add action points:
- [x] Wrapper function to import from kallisto .h5 files, using sleuth_prep.
- [x] Wrapper function to import from salmon/sailfish files using wasabi and sleuth_prep.

**Comment by fruce-ki** [comment]
`quant.sf` files from salmon don't contain the bootstrapped estimates. They are delimited text tables that only contain the averaged abundances.

Using the `quant.sf` file with RATs is very easy with the existing provisions:

```
# Load two files
sfA <- as.data.table(read.delim("pathA/quant.sf"))
sfB <- as.data.table(read.delim("pathB/quant.sf"))

# Tell RATs which columns are the IDs and counts.
# The other columns will be ignored.
mydtu <- call_DTU(annot= myannot, count_data_A= sfA, count_data_B= sfB, COUNTS_COL="NumReads", BS_TARGET_ID="Name")
```

In retrospect, it is not clear from the vignette that the two parameters apply to all input types, not just sleuth.


With regards to reading the [salmon](https://github.com/COMBINE-lab/salmon) and [kallisto](https://pachterlab.github.io/kallisto/about) bootstraps directly, they use different binary formats that I know nothing about. Given that [wasabi](https://github.com/COMBINE-lab/wasabi) and [sleuth](http://pachterlab.github.io/sleuth/) already provide converters/parsers, I am not inclined to re-invent the wheel. These parsers are written by the salmon and kallisto people respectively, and as such I trust them more than anything I'd write. At best I could write a wrapper function that calls them for you...

I will think about whether it is worth writing a wrapper function and adding wasabi and sleuth as package dependencies.

In the meantime, you don't need to run the DTE step of sleuth for RATs to be able to extract data. Just do the data import with `sleuth_prep()`. That creates an object that has everything RATs needs, without the weighty model fitting of DTE. It is a bit of code overhead, but you can save that object for later re-use.
Implementing a bespoke parser won't save you much typing. You'd still need to specify the multiple replicate paths for each condition.

**Comment by fruce-ki** [comment]
Reading back, I realised the `.sf` solution is missing replicates. So maybe there is scope for a wrapper that reads and merges multiple tables.

**Comment by fruce-ki** [comment]
Another issue with using `quant.sf` directly, is that TPMs are too small for the type of tests used in RATs, whereas NumReads are presumably not normalised for Transcript length or sequence bias.
Kallisto/wasabi/sleuth's `est_counts` are a better representation of the abundances.

**Comment by jamespblloyd** [comment]
Okay, so it sounds like going via the Sleuth object is for the best for various reasons then. Thanks for looking into this and I will continue to use the sleuth objects as inputs into RATs given how it deals with bio reps, normalization and bootstraps. Thanks!

**Comment by fruce-ki** [comment]
Even without fitting models, the sleuth object is pretty huge. In a human dataset I tried, the sleuth takes up 8GB when the extracted bootstrapped abundances take up "only" 800MB. This is some very serious overhead!
So at some point, when I have time to play, I should look into working out a solution that bypasses the sleuth loader altogether. Probably not in time for the next release though.
