### ISSUE TITLE
Need to Use Rep() in call_dtu

### ISSUE THREAD

**Issue by Tenayav** [bartongroup/RATS#71]
Hi!  

I am a biochemist, learning to code and wanted to reach out about some troubles I'm having with running RATs with my data. My research question is to find out which isoform is more abundant in a particular sample compared to another. RATs seemed like a good fit.  I'm using data from Salmon running in NF-core and in TPMs. Below are the details. Any suggestions would be most helpful!  Thank you for putting together RATs and maintaining it! 

The problem that I am running into is mismatch between item numbers.  

> Error in `[.data.table`(Genes, , `:=`(elig_transc, Transcripts[, as.integer(sum(elig, : Supplied 21207 items to be assigned to 59385 items of column 'elig_transc'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.

Version: Relative Abundance of Transcripts v.0.6.7
TPM data.table from Salmon -> See screenshot 
Annot, mycond_A, and mycond_B -> See screenshots.
Data should be in TPM. I'm still trying to figure out whether it is bootstrapped or not, but I figured I could get started on what I have. I ended up rounding my data to get integers, otherwise there are 6 decimal points.  

My Script: 

> targets <- txs_tpm[c(1)]
> frac2 <- data.table(txs_tpm[c(1,6,16)] )   # Simulated abundances for fraction 2
> frac2_A <- round(frac2[,c(2,3)], digits=0)
> frac2 <- data.table(cbind(targets, frac2_A))
> 
> colnames(frac2)<- c("target","V1","V2")
> 
> frac5 <- data.table(txs_tpm[c(1,9,19)])   # Simulated abundances for fraction 5
> frac5_A <- round(frac5[,c(2,3)], digits=0)
> frac5 <- data.table(cbind(targets, frac5_A))
> colnames(frac5)<- c("target","V1","V2")
> 
> annot <- data.frame(txs_tpm[c(1,3)])       # Transcript and gene IDs for the above data.
> colnames(annot)<- c("target_id", "parent_id")
> 
> mydtu <- call_DTU(annot= annot, count_data_A= frac2, 
>                   count_data_B= frac5, verbose=TRUE, scaling=1,
>                   name_A= "Fraction 2", name_B= "Fraction 5",
>                   varname= "Fractions",
>                   description="Comparison of Fraction 2 and Fraction 5 Cell Extracts from Rep1 after Threshold and in TPMS. RATs analysis.")
> 

Attempts to fix the error: 
rep(call_dtu(....)) -> Same error message
rep_lin(call_dtu(...), nrow(dat)) -> Same erro message
Running smaller number of genes, 3 or even 11. Still having the same problem. But I don't have this problem when I run the Simdata so I figure it's a problem with my data, not the script. 

<img width="831" alt="TPM_datatable" src="https://user-images.githubusercontent.com/60827780/222261531-c1b3c0ef-af4c-4cbe-ab54-ca2c3e1194c8.png">
<img width="298" alt="mycond_B_Frac5" src="https://user-images.githubusercontent.com/60827780/222261537-eaa3a2d0-0417-4986-934b-0cfa67ab0ace.png">
<img width="297" alt="mycond_A_Frac2" src="https://user-images.githubusercontent.com/60827780/222261538-81195bc4-1ca7-44d9-816d-1c0ca4bd004c.png">
<img width="294" alt="myannot" src="https://user-images.githubusercontent.com/60827780/222261541-630560bc-592b-4a2e-aae6-e9cb31fd254c.png">

**Comment by fruce-ki** [comment]
Hi!

The error is not making much sense to me and I do not see any obvious issue in the screenshots.

Can you please attach a small subset of the data tables and the corresponding subset of the annotation (that still produces the error for you) as actual text files so that I can try to run them and poke around?

**Comment by Tenayav** [comment]
Of course!  Thank you for taking a look at this. I downloaded them as csv files. Hope those work for text files!

Best,
Tenaya
[myannot.csv](https://github.com/bartongroup/RATS/files/10884429/myannot.csv)
[mycond_B.csv](https://github.com/bartongroup/RATS/files/10884430/mycond_B.csv)
[mycond_A.csv](https://github.com/bartongroup/RATS/files/10884431/mycond_A.csv)

**Comment by fruce-ki** [comment]
<img width="842" alt="Screenshot 2023-03-06 at 19 38 04" src="https://user-images.githubusercontent.com/18140986/223201445-3eab05f4-f89c-4ba2-a377-f622acc591d7.png">

CSV is excellent for the job. I assume the row number column is an artifact of exporting without explicitly telling it not to write the rownames. So I deleted that column from each file.

I then ran your files, and I got no error whatsoever. See screenshot. What are you doing differently?

**Comment by fruce-ki** [comment]
Can you do the checks as in my screenshot and post the verbose console output from those and from call_DTU() down to and including the error? That would narrow down what section is throwing the error.

**Comment by Tenayav** [comment]
Sure thing!  It was easy to run.  Here is a screenshot and text file of the checks and error message.  Thank you for your help! The row number is an artifact. Sorry about that!
<img width="762" alt="Screen Shot 2023-03-06 at 12 10 43 PM" src="https://user-images.githubusercontent.com/60827780/223207632-c0e28349-0a8a-4c8b-b6de-98c417016cee.png">
[2023_03_06_RATs_Kimon_Checksrequest.txt](https://github.com/bartongroup/RATS/files/10902022/2023_03_06_RATs_Kimon_Checksrequest.txt)

**Comment by Tenayav** [comment]
Oh and to cover bases, I did a clean sweep of my environment before trying the above. Just in case!

**Comment by fruce-ki** [comment]
I don't see anything wrong with that. Something must have changed in the 3rd party libraries.

Can you post your sessionInfo() ?

**Comment by Tenayav** [comment]
Can do!  Here it is! 
[2023_03_06_Sessioninfo.txt](https://github.com/bartongroup/RATS/files/10902104/2023_03_06_Sessioninfo.txt)

**Comment by fruce-ki** [comment]
So you have older versions of R etc. 

I tried to install the same versions as you, but the combination of versions is not available for Mac. Likely the issue is in one of the dependencies.

Can you try upgrading to newer versions and see if that fixes your problem?

**Comment by Tenayav** [comment]
Definitely trying. Our institution's server is sorely behind on updating R and it makes things complicated for us. I'm currently struggling on GRanges, but hoping to have all the dependencies updated for R/4.2.2 version soon.

**Comment by fruce-ki** [comment]
You should have more freedom with conda environments within your user space. Linux should have all the "normal" versions of R, unlike Mac.

**Comment by Tenayav** [comment]
Sorry for taking so long. I had to update everything and switch to my personal computer because of admin limitations on both my school server and my work laptop.  Your suggestion worked perfectly!  Thank you! Feel free to marked this as resolved.

**Comment by fruce-ki** [comment]
Good to hear! I am glad it worked out. There's probably documentation I need to update with regards to recommended versions for dependencies...
