### ISSUE TITLE
Fully eligible transcripts get NA as their DTU call

### ISSUE THREAD

**Issue by fruce-ki** [bartongroup/RATS#8]
This due to boot_dtu_freq being calculated as NA by matrixStats::rowCounts(), despite the presence of numeric values. 
This behaviour is stochastic and seems to be tightly connected to the the value of some bootstraps iterations being NA (i.e. too low count to be eligible): Non-zero frequency of NA values in the iterations for a transcript triggers failure of matrixStats::rowCounts().

**Comment by nickschurch** [comment]
sound like we might have to implement our own version of this function....

**Comment by fruce-ki** [comment]
@nickschurch Nope. It is common for descriptive stats functions to freak out over the presence of NAs and return NA. Standard workaround is passing the `na.rm=TRUE` parameter. Which I had done for all the other calls to stats functions except for the counting one. 

Besides, we're talking about a C code function. I'm absolutely not crossing that line into hybrid world.
