### ISSUE TITLE
Saving gene plots...

### ISSUE THREAD

**Issue by nickschurch** [bartongroup/RATS#9]
It would be nice to add some keyword arguments to plot_gene to allow the plot to be saved directly to a file as well as displayed. That would allow lists of genes with sDTU to be looped over quickly and output all their plots, rather than the laborious click-and-save required at the moment.

**Comment by fruce-ki** [comment]
It is not typical practice for plotting functions in R to output directly to files. The desired result can easily be achieved using standard R output redirection as follows:

`pdf("path/my_gene_plot.pdf")`
` print( plot_gene(my_dtu, my_gene_id) )`
`dev.off()`

A looping structure added inside or around these 3 lines can easily pile a boat-load of plots into one or multiple files, as desired.
